import json
from glob import glob
from pathlib import Path
from markdown import markdown

# TODO : add a proper project title to the page!
def inject_html(html_content: str):
  return f'''<!-- this file is auto-generated by ./build.py -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Markdown + MathJax</title>
        <link rel="stylesheet" href="../../css/base.css">
        <script> <!-- Configure MathJax to process $...$ -->
            window.MathJax = {{
                tex: {{
                    inlineMath: [['$', '$']],
                    displayMath: [['$$','$$']]
                }}
            }};
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    </head>
    <body>
        {html_content}
    </body>
</html>
'''

def main() -> None :
    project_paths = list(map(Path, glob('./content/*')))

    projects = []
    print('building...')
    for (i, p) in enumerate(project_paths): 
        # reading project meta, to be added to projects.json
        with open(p.joinpath('info.json'), 'r') as handle : 
            info = json.load(handle)
            info['root'] = str(p)
            projects.append(info)

        # reading and parsing the markdown file:
        with open(p.joinpath('main.md'), 'r') as handle :
            md = ''.join(handle.readlines())
        html = inject_html(markdown(md))
        # exporting the .html
        with open(p.joinpath('main.html'), 'w') as handle :
            handle.writelines(html)

        print(f'[{i+1:03d}/{len(project_paths):03d}]', p.name)

    # exporting all project meta data to draw the tiles
    with open('./projects.json', 'w') as handle :
        json.dump(projects, handle)

if (__name__ == '__main__') : main()