var $jscomp$this=this;WozViewer={init:function(){$(window).load(function(){WozViewer.Properties.init();WozViewer.OLMap.init();WozViewer.Geocoder.init();WozViewer.Filter.init();WozViewer.Filter.Panden.init();WozViewer.Filter.Selection.init();WozViewer.Print.init();WozViewer.Popup.init();WozViewer.WfsService.init();WozViewer.BusyIndicator.init();WozViewer.Queryparameters.process();$("input","#geocode").focus()})}};WozViewer.init();$(document).keydown(function(a){27===a.keyCode&&$.window.closeAll()});
WozViewer.Util={setactualiteit:function(){WozViewer.WfsService.getActualiteit(function(a){0<a.length&&(WozViewer.Properties.actualiteit=WozViewer.Util.formatActualiteitdatum(a[0].properties.wact_laatste_aanlevering),$("#actualiteitsdatum").html(WozViewer.Properties.actualiteit))})},formatMoney:function(a,b,c,e,g){a=a||0;b=isNaN(b=Math.abs(b))?2:b;c=void 0!==c?c:"$";e=e||".";g=g||",";var h=0>a?"-":"",f=parseInt(a=Math.abs(+a||0).toFixed(b),10)+"",k=3<(k=f.length)?k%3:0;return c+h+(k?f.substr(0,k)+
e:"")+f.substr(k).replace(/(\d{3})(?=\d)/g,"$1"+e)+(b?g+Math.abs(a-f).toFixed(b).slice(2):"")},formatWozWaarde:function(a){return this.formatMoney(a,0,"")+" euro"},formatPostCode:function(a){return a?a.substring(0,4)+" "+a.substring(4,6):a},formatPeildatum:function(a){return a},formatActualiteitdatum:function(a){var b=new Date(a);a=b.getDate();var c=b.getMonth()+1,b=b.getFullYear();return(10>a?"0":"")+a+"-"+(10>c?"0":"")+c+"-"+b},TryParseInt:function(a,b){null!==a&&0<a.toString().length&&(isNaN(a)||
(b=parseInt(a)));return b},showElement:function(a){$(a).removeClass("hidden")},showServerError:function(a){$.window({draggable:!1,resizable:!1,minimizable:!1,maximizable:!1,showModal:!0,frameClass:"dialog",height:100,z:6E3,title:"Server waarschuwing",content:'\x3cspan class\x3d"dialog"\x3e'+a+"\x3c/span\x3e"})},hideElement:function(a){$(a).addClass("hidden")},formatAddress:function(a,b,c,e){var g;g=e&&0<e.length?"-"+e:"";b=c&&0<c.length?b?b+c+g:c+g:b?b+g:e||"";return a?a+" "+b:b},formatSortAddress:function(a,
b,c,e){a=(WozViewer.Util.isNullUndefined(a)?"":a)+" ";b=(WozViewer.Util.isNullUndefined(b)?"":this.formatPad(b,6))+" ";c=WozViewer.Util.isNullUndefined(c)?" ":c;e=WozViewer.Util.isNullUndefined(e)?" ":e;return sprintf("%s%6s%1s%5s",a,b,c,e)},formatPad:function(a,b){void 0===a&&(a="0");return a.length>=b?a:(Math.pow(10,b)+Math.floor(parseInt(a))).toString().substring(1)},isNullUndefined:function(a){return null===a||void 0===a?!0:!1},formatnvt:function(a){return null===a||void 0===a||""==a?"n.v.t.":
a},coordinatesFromString:function(a){var b=parseFloat(a.split(" ")[0]);a=parseFloat(a.split(" ")[1]);return{x:b,y:a}},padBagId:function(a){for(a+="";16>a.length;)a="0"+a;return a},url:function(a){var b=$("\x3cform /\x3e");b.attr("action",a);b.attr("method","POST");b.append('\x3cinput type\x3d"hidden" name\x3d"accept" value\x3d"true"/\x3e');$("body").append(b);b.submit();return!1}};
WozViewer.Properties={currentYear:(new Date).getFullYear(),serverName:null,color:null,defaultColor:"ffaa00",pdokServerUrl:"http://geodata.nationaalgeoregister.nl",proxyUrl:"woz-proxy/",pdfUrl:"woz-pdf",reportserviceUrl:"/reportservice/",wozWfsUrl:"wozloket",bagWfsUrl:"bag",filterUrl:"filter",geocoderSuggestUrl:"api/geocoder/v3/suggest",geocoderLookupUrl:"api/geocoder/v3/lookup",pdokWmsUrl:null,pdokFotoUrl:null,wfsmaxfeatures:null,wfsmaxfilterfeatures:null,actualiteit:null,init:function(){$.ajax({type:"GET",
url:"url-info",data:"search\x3dall",success:function(a){WozViewer.Properties.pdokWmsUrl=a.pdokwmsurl;WozViewer.Properties.pdokFotoUrl=a.pdokfotourl;WozViewer.Properties.wfsmaxfeatures=a.WFS_MAX_FEATURES},async:!1});WozViewer.Util.setactualiteit()}};
(function(a,b){var c,e=function(){var a=b("#zoeklocatieSubmit"),d=b("#zoeklocatie"),c=b("form","#geocode"),f=b("#adLijst"),e=function(b){a.button({disabled:!b})};e(!1);d.keyup(function(){e(0!=d.val().length)});return{setEnabledSubmitButton:e,setSubmitHandler:function(a){c.submit(function(){a(d.val());return!1})},noSuggestionsFound:function(){b("\x3cspan\x3eNiets gevonden\x3c/span\x3e").appendTo(f)},addSuggestion:function(a){b('\x3ca href\x3d"#" onclick\x3d"'+("WozViewer.Geocoder.selectSuggestion('"+
a.id+"'); return false;")+'"\x3e'+a.weergavenaam+"\x3c/a\x3e\x3cbr\x3e").appendTo(f)},clearSuggestions:function(){f.empty()}}},g=function(a){c.clearSuggestions();k(a,{onSucces:function(a){c.clearSuggestions();0===a.docs.length?c.noSuggestionsFound():(b.each(a.docs,function(a,b){c.addSuggestion(b)}),1===a.docs.length&&h(a.docs[0].id))},onError:function(a){console.log("Fout bij het ophalen van suggesties: ",a)}});WozViewer.Filter.resetSliders()},h=function(a){m(a,{onSucces:function(a){f(a)},onError:function(a){console.log("Fout bij het gegevens van geocoderservice: ",
a)}})},f=function(a){WozViewer.Filter.removeFilter();WozViewer.Util.hideElement(b("li#panden"));WozViewer.Filter.Selection.resetSelectionResult();WozViewer.OLMap.layerPolygoon.removeAllFeatures();var d=(a.nlt||"").split("-"),c=""+(a.huisnummer||""),l=1<d.length?d[1]:"",d=d[0].length>c?d[0].substring(c.length):"";WozViewer.Filter.Selection.setSelectedAdres({postcode:a.postcode,huisnummer:a.huisnummer,huisletter:d,toevoeging:l});l=a.adresseerbaarobject_id;d=a.centroide_rd.x;a=a.centroide_rd.y;WozViewer.OLMap.centerMap(new OpenLayers.LonLat(d,
a),!1,5);WozViewer.Filter.Selection.selectObjectByXY(d,a,l);WozViewer.Filter.invalidateFilter();WozViewer.Util.hideElement(b("#panden"))},k=function(a,b){d(WozViewer.Properties.geocoderSuggestUrl+"?query\x3d"+a,b)},m=function(a,b){d(WozViewer.Properties.geocoderLookupUrl+"?id\x3d"+a,b)},d=function(a,d){b.ajax({type:"GET",url:a,success:function(a){d.onSucces(a)},error:function(a,b,c){if(0!==a.status||0!==a.readyState)if(console.log("url",WozViewer.Properties.geocoderLookupUrl+"?id\x3d"+id),d.onError)d.onError(c)}})};
a.Geocoder={init:function(){c=e();c.setSubmitHandler(function(a){g(a)})},showSuggestions:g,selectSuggestion:h,selectLookupItem:f}})(WozViewer,jQuery);
WozViewer.OLMap={verblijfsobjectFeature:null,wozObjectFeature:null,map:null,options:null,layerBRT:null,layerLuchtfoto:null,layerLuchtfotoLabels:null,layerBag:null,layerBagSelection:null,layerPolygoon:null,layerSelectPolygoon:null,VECTOR_LAYERS_MIN_ZOOMLEVEL:5,LUCHTFOTO_LABELS_MIN_ZOOMLEVEL:2,MAX_AREA:22E5,useOpacity:!0,bagBaseOpacity:.3,bagFadedOpacity:.1,numZoomLevels:6,init:function(){OpenLayers.ImgPath="resources/images/img/";OpenLayers.IMAGE_RELOAD_ATTEMPTS=3;$.browser.msie&&8>=parseInt($.browser.version)&&
(this.useOpacity=!1);this.initLayers();this.initMap();this.registerMapEvents();this.initLayerButtons()},initLayers:function(){this.layerBRT=new OpenLayers.Layer.WMTS({name:"BRT Achtergrondkaart",url:WozViewer.Properties.pdokWmsUrl+"/tiles/service/wmts/?",layer:"brtachtergrondkaart",matrixSet:"EPSG:28992",matrixIds:[{identifier:"EPSG:28992:3"},{identifier:"EPSG:28992:5"},{identifier:"EPSG:28992:7"},{identifier:"EPSG:28992:9"},{identifier:"EPSG:28992:11"},{identifier:"EPSG:28992:13"}],format:"image/png8",
style:"_null",visiblity:!1,isBaseLayer:!0,buffer:0});this.layerLuchtfoto=new OpenLayers.Layer.WMTS({name:"Luchtfoto's",url:WozViewer.Properties.pdokFotoUrl+"/",layer:"Actueel_ortho25",matrixSet:"EPSG:28992",matrixIds:[{identifier:"03"},{identifier:"05"},{identifier:"07"},{identifier:"09"},{identifier:"11"},{identifier:"13"}],format:"image/jpeg",style:"default",visiblity:!1,isBaseLayer:!0,buffer:0});this.layerLuchtfotoLabels=new OpenLayers.Layer.WMTS({name:"LuchtfotoLabels",url:WozViewer.Properties.pdokWmsUrl+
"/tiles/service/wmts/?",layer:"lufolabels",matrixSet:"EPSG:28992",matrixIds:[{identifier:"EPSG:28992:3"},{identifier:"EPSG:28992:5"},{identifier:"EPSG:28992:7"},{identifier:"EPSG:28992:9"},{identifier:"EPSG:28992:11"},{identifier:"EPSG:28992:13"}],format:"image/png",style:"_null",visiblity:!1,isBaseLayer:!1,buffer:0});this.layerLuchtfotoLabels.setVisibility(!1);this.layerBag=new OpenLayers.Layer.WMTS({name:"BAG Panden",url:WozViewer.Properties.pdokWmsUrl+"/tiles/service/wmts/?",layer:"bag",matrixSet:"EPSG:28992",
matrixIds:[{identifier:"EPSG:28992:3"},{identifier:"EPSG:28992:5"},{identifier:"EPSG:28992:7"},{identifier:"EPSG:28992:9"},{identifier:"EPSG:28992:11"},{identifier:"EPSG:28992:13"}],format:"image/png8",style:"_null",visiblity:!1,isBaseLayer:!1,buffer:0});this.layerBag.setVisibility(!1);this.layerBagSelection=new OpenLayers.Layer.WMS("BAG - selectie",[WozViewer.Properties.pdokServerUrl+"/bag/wms?SERVICE\x3dWMS"],{layers:"pand",format:"image/png",transparent:!0,styles:"WozViewer_pand_selected"},{isBaseLayer:!1,
visibility:!1,maxResolution:1.68,buffer:0,singleTile:!0});var a=new OpenLayers.StyleMap({fillColor:"#"+WozViewer.Properties.defaultColor,fillOpacity:.5,strokeColor:"#707070",strokeWidth:2}),b=new OpenLayers.StyleMap({fillColor:"#f9e11e",fillOpacity:1,strokeColor:"black",strokeWidth:3});this.layerPolygoon=new OpenLayers.Layer.Vector("Vector Layer",{styleMap:b,projection:new OpenLayers.Projection("EPSG:28992")});this.layerSelectPolygoon=new OpenLayers.Layer.Vector("Vector Layer",{styleMap:a,projection:new OpenLayers.Projection("EPSG:28992")});
this.useOpacity&&(this.layerBag.setOpacity(this.bagBaseOpacity),this.layerBagSelection.setOpacity(this.bagBaseOpacity));a=new OpenLayers.StyleMap({fillColor:"white",pointRadius:5,strokeColor:"black",strokeWidth:2});this.layerVerblijfPoint=new OpenLayers.Layer.Vector("Verblijflayer",{styleMap:a,projection:new OpenLayers.Projection("EPSG:28992")})},initMap:function(){this.options={projection:"EPSG:28992",attribution:"WOZ-waardeloket",displayProjection:new OpenLayers.Projection("EPSG:28992"),units:"m",
restrictedExtent:new OpenLayers.Bounds(0,3E5,3E5,63E4),maxExtent:new OpenLayers.Bounds(-285401.92,22598.08,595401.92,903401.92),resolutions:[430.08,107.52,26.88,6.72,1.68,.42],controls:[new OpenLayers.Control.Navigation,new OpenLayers.Control.PanZoomBar,new OpenLayers.Control.KeyboardDefaults,new OpenLayers.Control.Attribution],maxResolution:430.08,theme:"resources/css/theme/default/style.css"};this.map=new OpenLayers.Map("map",this.options);this.map.addLayers([this.layerBRT,this.layerLuchtfoto,this.layerLuchtfotoLabels,
this.layerBag,this.layerBagSelection,this.layerSelectPolygoon,this.layerPolygoon,this.layerVerblijfPoint]);this.map.setCenter(new OpenLayers.LonLat(16E4,455E3),0);$(".olTileImage,.olAlphaImg").attr("alt","")},registerMapEvents:function(){this.map.events.register("click",this.map,function(a){resetIdleTimer();WozViewer.OLMap.map.zoom>=WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL&&(a=WozViewer.OLMap.map.getLonLatFromViewPortPx(new OpenLayers.Pixel(a.xy.x,a.xy.y)),WozViewer.Filter.Panden.clearSelectionTablePand(),
WozViewer.Filter.Selection.setSelectedAdres({}),WozViewer.Filter.Selection.selectObjectByXY(a.lon,a.lat));return!1});this.map.events.register("movestart",this.map,function(a){resetIdleTimer();a.zoomChanged&&WozViewer.OLMap.hideLuchtfotoLabels();WozViewer.Filter.invalidateFilter();WozViewer.OLMap.map.zoom>=WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL?WozViewer.OLMap.showVectorLayers():WozViewer.OLMap.hideVectorLayers()});this.map.events.register("updatesize",this.map,function(a){resetIdleTimer();$(".olTileImage,.olAlphaImg").attr("alt",
"")});this.map.events.register("moveend",this.map,function(a){resetIdleTimer();$(".olTileImage,.olAlphaImg").attr("alt","")});this.map.events.register("zoomend",this.map,function(a){resetIdleTimer();WozViewer.Filter.invalidateFilter();WozViewer.OLMap.map.zoom>=WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL?(WozViewer.OLMap.showBAGPanden(),WozViewer.OLMap.showVectorLayers(),1<$("#dataTablePand a").length&&WozViewer.Util.showElement($("#panden"))):(WozViewer.OLMap.hideBAGPanden(),WozViewer.OLMap.hideVectorLayers(),
WozViewer.Util.hideElement($("#panden")));WozViewer.OLMap.map.baseLayer==WozViewer.OLMap.layerLuchtfoto?WozViewer.OLMap.showLuchtfotoLabels():WozViewer.OLMap.hideLuchtfotoLabels();$(".olTileImage,.olAlphaImg").attr("alt","")})},initLayerButtons:function(){$("#switchBRT").attr("checked","checked");$("#layers").buttonset();$("#switchBRT").click(function(){resetIdleTimer();WozViewer.OLMap.map.setBaseLayer(WozViewer.OLMap.layerBRT);WozViewer.OLMap.hideLuchtfotoLabels();return!1});$("#switchLuchtfoto").click(function(){resetIdleTimer();
WozViewer.OLMap.map.setBaseLayer(WozViewer.OLMap.layerLuchtfoto);WozViewer.OLMap.showLuchtfotoLabels();return!1})},showLuchtfotoLabels:function(){this.layerLuchtfotoLabels.setVisibility(WozViewer.OLMap.map.zoom>=WozViewer.OLMap.LUCHTFOTO_LABELS_MIN_ZOOMLEVEL)},hideLuchtfotoLabels:function(){this.layerLuchtfotoLabels.setVisibility(!1)},showBAGPanden:function(){this.layerBag.setVisibility(!0)},hideBAGPanden:function(){this.layerBag.setVisibility(!1)},showVectorLayers:function(){this.layerPolygoon.setVisibility(!0);
this.layerSelectPolygoon.setVisibility(!0)},hideVectorLayers:function(){this.layerPolygoon.setVisibility(!1);this.layerSelectPolygoon.setVisibility(!1)},getBbox:function(){return this.map.getExtent().toGeometry()},centerMap:function(a,b,c){this.map.setCenter(a,c);b&&(a=this.map.getViewPortPxFromLonLat(a),this.showLocation(a.x,a.y))},centerFeature:function(a){var b=this.verblijfsobjectFeature||this.wozObjectFeature;b&&b.geometry&&this.centerMap(this.lonlatFromFeature(b),a)},showLocationOfFeature:function(a){a=
this.lonlatFromFeature(a);a=this.map.getViewPortPxFromLonLat(a);this.showLocation(a.x,a.y)},lonlatFromFeature:function(a){a=a.geometry.getCentroid();return new OpenLayers.LonLat(a.x,a.y)},showLocation:function(a,b){a-=$("#crosshair").width()/2;b-=$("#crosshair").height()/2;$("#crosshair").css({left:a,top:b});$("#crosshair").delay(150).fadeIn("fast").delay(250).fadeOut("fast")},drawSelectedFeature:function(a){WozViewer.OLMap.layerPolygoon.removeAllFeatures();a&&a.geometry?(this.wozObjectFeature=(new OpenLayers.Format.GeoJSON({ignoreExtraDims:!0})).parseFeature({geometry:a.geometry}),
WozViewer.OLMap.layerPolygoon.addFeatures(this.wozObjectFeature)):this.wozObjectFeature=null},showLocationOfSelectedVerblijfsobject:function(){this.verblijfsobjectFeature&&WozViewer.OLMap.showLocationOfFeature(this.verblijfsobjectFeature)},drawVerblijfsobjectFeature:function(a){WozViewer.OLMap.layerVerblijfPoint.removeAllFeatures();a&&a.geometry?(this.verblijfsobjectFeature=(new OpenLayers.Format.GeoJSON({ignoreExtraDims:!0})).parseFeature(a),WozViewer.OLMap.layerVerblijfPoint.addFeatures(this.verblijfsobjectFeature)):
this.verblijfsobjectFeature=null},resetSelectedObject:function(){this.drawSelectedFeature(null);this.drawVerblijfsobjectFeature(null)}};
WozViewer.Filter={bouwjaarMin:0,bouwjaarMax:150,bouwjaarSplit:4,oppervlakteMin:0,oppervlakteMax:600,wozwaardeMin:0,wozwaardeMax:2E6,sliderBouwjaarActive:!1,sliderOppervlakteActive:!1,sliderWozwaardeActive:!1,sliderInfo:"\x26lsaquo; sleep om selectie aan te passen \x26rsaquo;",validated:!0,filtered:!1,filteredExtent:null,init:function(){this.initSliders();this.initButtons();WozViewer.Filter.invalidateFilter()},initSliders:function(){this.sliderBouwjaarActive=this.sliderOppervlakteActive=this.sliderWozwaardeActive=
!1;$("#wozwaarde .slider").slider({range:!0,min:this.wozwaardeMin,max:this.wozwaardeMax,values:[this.wozwaardeMin,this.wozwaardeMax],step:25E3,slide:function(a,b){WozViewer.Filter.updateWozwaardeLabel(b.values[0],b.values[1]);WozViewer.Filter.invalidateFilter()}});this.updateWozwaardeLabel(this.getWozwaardeFrom(),this.getWozwaardeTo());$("#wozwaarde .reset").button();$("#wozwaarde .reset").click(function(){WozViewer.Filter.resetWozwaarde()});$("#bouwjaar .slider").slider({range:!0,min:WozViewer.Filter.bouwjaarMin,
max:WozViewer.Filter.bouwjaarMax,values:[WozViewer.Filter.bouwjaarMin,WozViewer.Filter.bouwjaarMax],slide:function(a,b){WozViewer.Filter.updateBouwjaarLabel(b.values[0],b.values[1]);WozViewer.Filter.invalidateFilter()}});this.updateBouwjaarLabel(this.getBouwjaarFrom(),this.getBouwjaarTo());$("#bouwjaar .reset").button();$("#bouwjaar .reset").click(function(){WozViewer.Filter.resetBouwjaar()});$("#oppervlakte .slider").slider({range:!0,min:this.oppervlakteMin,max:this.oppervlakteMax,values:[this.oppervlakteMin,
this.oppervlakteMax],slide:function(a,b){WozViewer.Filter.updateOppervlakteLabel(b.values[0],b.values[1]);WozViewer.Filter.invalidateFilter()}});this.updateOppervlakteLabel(this.getOppervlakteFrom(),this.getOppervlakteTo());$("#oppervlakte .reset").button();$("#oppervlakte .reset").click(function(){WozViewer.Filter.resetOppervlakte()})},initButtons:function(){$("#apply","#buttons").button({disabled:!0}).click(function(){$("input","#geocode").val("");WozViewer.Util.hideElement($("#panden"));WozViewer.Filter.applyFilter()||
alert("Gebied te groot voor selectie - zoom in of verklein browserscherm")});$("#reset","#buttons").button({disabled:!0}).click(function(){WozViewer.Filter.removeFilter();WozViewer.Filter.Panden.setFilterResult([]);WozViewer.Util.hideElement($("#panden"))})},getWozwaardeFrom:function(){return $(".slider","#wozwaarde").slider("values",0)},getWozwaardeTo:function(){return $(".slider","#wozwaarde").slider("values",1)},getBouwjaarFrom:function(){return $(".slider","#bouwjaar").slider("values",0)},getBouwjaarTo:function(){return $(".slider",
"#bouwjaar").slider("values",1)},getBouwjaar:function(a){return a==this.bouwjaarMax?0:a>=this.bouwjaarSplit?WozViewer.Properties.currentYear-(this.bouwjaarMax-this.bouwjaarSplit)+(a-this.bouwjaarSplit):a>=this.bouwjaarMin+1?this.round5(WozViewer.Properties.currentYear-(this.bouwjaarMax-this.bouwjaarSplit)-5*(this.bouwjaarSplit-a)-3):0},round5:function(a){return 2.5<=a%5?5*parseInt(a/5)+5:5*parseInt(a/5)},getBouwjaarLabel:function(a,b){a=this.getBouwjaar(a);b=this.getBouwjaar(b);var c=0!==a,e=0!==
b;this.sliderBouwjaarActive=c||e;return c||e?e?c?a+" tot "+b:"tot "+b:"vanaf "+a:""},updateBouwjaarLabel:function(a,b){a=this.getBouwjaarLabel(a,b);b="";a||(a="alles",b=this.sliderInfo);$(".ui-slider-range","#bouwjaar").html(b);$(".value","#bouwjaar").html(a)},resetBouwjaar:function(){$("#bouwjaar .slider").slider("option","values",[this.bouwjaarMin,this.bouwjaarMax]);this.updateBouwjaarLabel(this.bouwjaarMin,this.bouwjaarMax);this.sliderBouwjaarActive=!1;this.invalidateFilter()},getOppervlakteFrom:function(){return $(".slider",
"#oppervlakte").slider("values",0)},getOppervlakteTo:function(){return $(".slider","#oppervlakte").slider("values",1)},getOppervlakte:function(a){return a==this.oppervlakteMax?0:a==this.oppervlakteMin?0:a},getOppervlakteLabel:function(a,b){a=this.getOppervlakte(a);b=this.getOppervlakte(b);var c=0!==a,e=0!==b;this.sliderOppervlakteActive=c||e;return c||e?e?c?a+" mÂ² tot "+b+" mÂ²":"tot "+b+" mÂ²":"vanaf "+a+" mÂ²":""},getWozwaardeLabel:function(a,b){var c=a!==this.wozwaardeMin,e=b!==this.wozwaardeMax;
this.sliderWozwaardeActive=c||e;return c||e?e?c?WozViewer.Util.formatWozWaarde(a)+" tot "+WozViewer.Util.formatWozWaarde(b):"tot "+WozViewer.Util.formatWozWaarde(b):"vanaf "+WozViewer.Util.formatWozWaarde(a):""},updateWozwaardeLabel:function(a,b){a=this.getWozwaardeLabel(a,b);b="";a||(a="alles",b=this.sliderInfo);$(".ui-slider-range","#wozwaarde").html(b);$(".value","#wozwaarde").html(a)},updateOppervlakteLabel:function(a,b){a=this.getOppervlakteLabel(a,b);b="";a||(a="alles",b=this.sliderInfo);$(".ui-slider-range",
"#oppervlakte").html(b);$(".value","#oppervlakte").html(a)},resetOppervlakte:function(){$("#oppervlakte .slider").slider("option","values",[this.oppervlakteMin,this.oppervlakteMax]);this.updateOppervlakteLabel(this.oppervlakteMin,this.oppervlakteMax);this.sliderOppervlakteActive=!1;this.invalidateFilter()},resetWozwaarde:function(){$("#wozwaarde .slider").slider("option","values",[this.wozwaardeMin,this.wozwaardeMax]);this.updateWozwaardeLabel(this.wozwaardeMin,this.wozwaardeMax);this.sliderWozwaardeActive=
!1;this.invalidateFilter()},resetSliders:function(){this.resetBouwjaar();this.resetWozwaarde();this.resetOppervlakte()},invalidateFilter:function(){var a=WozViewer.OLMap.getBbox(),a=this.canFilter(a),b=this.anySliderActivated();$("#apply","#buttons").button("option","disabled",!a||!b);a?($("#select .content").removeClass("ui-state-disabled"),$("#select #buttons").removeClass("ui-state-disabled")):($("#select .content").addClass("ui-state-disabled"),$("#select #buttons").addClass("ui-state-disabled"));
$("#select .smallbutton").button("option","disabled",!a);$("#select .slider").slider({disabled:!a});this.validated=!1;WozViewer.Filter.Panden.setFilterResult([])},canFilter:function(a){a=a.getArea()<WozViewer.OLMap.MAX_AREA;return WozViewer.OLMap.map.zoom>=WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL&&a?!0:!1},sliderActivated:function(a){var b=a.slider("option","values"),c=a.slider("option","max"),e=a.slider("option","min");a.slider("option","step");return b[0]>e||b[1]<c?!0:!1},anySliderActivated:function(){return this.sliderBouwjaarActive||
this.sliderOppervlakteActive||this.sliderWozwaardeActive},createFilterData:function(){var a={};this.getWozwaardeFrom()!=this.wozwaardeMin&&(a.wozwaardeFrom=this.getWozwaardeFrom());this.getWozwaardeTo()!=this.wozwaardeMax&&(a.wozwaardeTo=this.getWozwaardeTo());var b=this.getBouwjaar(this.getBouwjaarFrom());0!==b&&(a.bouwjaarFrom=b);b=this.getBouwjaar(this.getBouwjaarTo());0!==b&&(a.bouwjaarTo=b);b=this.getOppervlakte(this.getOppervlakteFrom());a.oppervlakteFrom=0===b?.01:b;b=this.getOppervlakte(this.getOppervlakteTo());
0!==b&&(a.oppervlakteTo=b);return a},applyFilter:function(){var a=WozViewer.OLMap.getBbox();if(!this.filtered||!this.validated){if(this.canFilter(a)){this.validated=this.filtered=!0;var b=this.createFilterData(),a=null==a?null:a.getBounds();WozViewer.WfsService.filterWozObjects(b,a,function(a){var b=WozViewer.Filter.Selection.getWozObjecten(a);WozViewer.Filter.Panden.setFilterResult(b);WozViewer.OLMap.layerSelectPolygoon.removeAllFeatures();b=new OpenLayers.Format.GeoJSON({ignoreExtraDims:!0});WozViewer.OLMap.layerSelectPolygoon.addFeatures(b.read({type:"FeatureCollection",
totalFeatures:a.length,features:a}));WozViewer.OLMap.showVectorLayers();WozViewer.Util.showElement($("#panden"))});WozViewer.OLMap.useOpacity&&WozViewer.OLMap.layerBag.setOpacity(WozViewer.OLMap.bagFadedOpacity);this.filteredExtent=WozViewer.OLMap.map.getExtent();$("#apply","#buttons").button("option","disabled",!0);$("#reset","#buttons").button("option","disabled",!1);$("#reset").focus();return!0}return!1}},removeFilter:function(){this.filtered&&(this.filtered=!1,this.filteredExtent=null,WozViewer.OLMap.layerSelectPolygoon.setVisibility(!1),
WozViewer.OLMap.layerSelectPolygoon.removeAllFeatures(),WozViewer.OLMap.useOpacity&&WozViewer.OLMap.layerBag.setOpacity(WozViewer.OLMap.bagBaseOpacity),$("#reset","#buttons").button("option","disabled",!0),$("#apply","#buttons").button("option","disabled",!this.anySliderActivated()),$("#apply").focus())},zoomToFilter:function(){null===this.filteredExtent||this.validated||(WozViewer.OLMap.map.zoomToExtent(this.filteredExtent,!0),this.applyFilter())}};
(function(a,b){var c=null,e=[],g=function(a){return{identificatie:a.properties.wobj_obj_id,status:a.properties.wobj_status,adres:WozViewer.Util.formatAddress(a.properties.wobj_straat,a.properties.wobj_huisnummer,a.properties.wobj_huisletter,a.properties.wobj_toevoeging),sortField:WozViewer.Util.formatSortAddress(a.properties.wobj_straat,a.properties.wobj_huisnummer,a.properties.wobj_huisletter,a.properties.wobj_toevoeging),woonplaats:a.properties.wobj_woonplaats,postcode:a.properties.wobj_postcode,
huisnummer:a.properties.wobj_huisnummer,huisletter:a.properties.wobj_huisletter||"",toevoeging:a.properties.wobj_toevoeging||"",plaats:a.properties.wobj_plaats,bouwjaar:WozViewer.Util.formatnvt(a.properties.wobj_bouwjaar),gebruiksdoel:WozViewer.Util.formatnvt(a.properties.wobj_gebruiksdoel),oppervlakte:WozViewer.Util.formatnvt(a.properties.wobj_oppervlakte),geometry:a.geometry,wozInfo:a.wozInfo,type:"Woz"}},h=function(a,b){b||console.error("IllegalArgument type is "+b);var d=WozViewer.Util.formatAddress(WozViewer.Util.isNullUndefined(a.properties.straat)?
a.properties.openbare_ruimte:a.properties.straat,a.properties.huisnummer,a.properties.huisletter,a.properties.toevoeging),c=WozViewer.Util.formatSortAddress(WozViewer.Util.isNullUndefined(a.properties.straat)?a.properties.openbare_ruimte:a.properties.straat,a.properties.huisnummer,a.properties.huisletter,a.properties.toevoeging);return{id:a.properties.identificatie,identificatie:a.properties.identificatie,status:a.properties.status,adres:d,sortField:c,woonplaats:a.properties.woonplaats,postcode:a.properties.postcode,
huisnummer:a.properties.huisnummer,huisletter:a.properties.huisletter||"",toevoeging:a.properties.toevoeging||"",plaats:a.properties.woonplaats,bouwjaar:WozViewer.Util.formatnvt(a.properties.bouwjaar),gebruiksdoel:WozViewer.Util.formatnvt(a.properties.gebruiksdoel),oppervlakte:WozViewer.Util.formatnvt(a.properties.oppervlakte),geometry:a.geometry,wozInfo:null,type:b}},f=function(a){var d={};b.each(a,function(a,b){d[b.properties.wobj_obj_id]||(d[b.properties.wobj_obj_id]=[]);d[b.properties.wobj_obj_id].push(b)});
return d},k=function(a){for(var b=[],d,c=0;c<a.length;c++){d=a[c];for(var f=!1,e=0;e<b.length;e++)b[e][0]===d.properties.wobj_wrd_peildatum&&(f=!0);!f&&d.properties.wobj_wrd_peildatum&&d.properties.wobj_wrd_woz_waarde&&b.push([d.properties.wobj_wrd_peildatum,d.properties.wobj_wrd_woz_waarde])}return b},m=function(a){if(!a||0==a.length)return null;var d=b.grep(a,function(a){return a.properties.wobj_gebruiksdoel&&0<=a.properties.wobj_gebruiksdoel.indexOf("woonfunctie")});d&&0!==d.length||(d=a);var c=
d[0];b.each(d,function(a,b){b.properties.wobj_oppervlakte&&b.properties.wobj_oppervlakte>(c.properties.wobj_oppervlakte||0)&&(c=b)});c.wozInfo=k(a);return c};a.Selection={selectedAddress:{},init:function(){b(".crosshair","#polygoon").button();b(".crosshair","#polygoon").click(function(){WozViewer.Filter.Selection.zoomToPolygoon()});b(".close","#polygoon").button();b(".close","#polygoon").click(function(){WozViewer.Filter.Selection.resetSelectionResult()})},fillWozWithBagIfNecessary:function(){if(!(0<
e.length))for(var a=0;a<this.pandobjecten.length;a++){var b={identificatie:this.pandobjecten[a].identificatie,status:this.pandobjecten[a].status,bouwjaar:WozViewer.Util.formatnvt(this.pandobjecten[a].bouwjaar),gebruiksdoel:WozViewer.Util.formatnvt(this.pandobjecten[a].gebruiksdoel),oppervlakte:WozViewer.Util.formatnvt(this.pandobjecten[a].oppervlakte),geometry:this.pandobjecten[a].geometry,sortField:this.pandobjecten[a].identificatie,wozInfo:null,type:"Pand"};e.push(b)}},getWozObjecten:function(a,
c,k){var d=[];if(0>=a.length)return d;if(void 0===a[0].properties.wobj_obj_id)return this.getBagObjecten(a,c,k),this.fillWozWithBagIfNecessary(),e;a=f(a);b.each(a,function(a,b){a=m(b);a=g(a);d.push(a)});return e=d},getBagObjecten:function(a,b,c){e=[];if(!(0>=a.length)){this.pandobjecten=[];for(var d=0;d<a.length;d++)if("Ligplaats"===b||"Standplaats"===b){var f=h(a[d],b);e.push(f)}else f={identificatie:a[d].properties.identificatie,gebruiksdoel:a[d].properties.gebruiksdoel,oppervlakte:a[d].properties.oppervlakte_max,
bouwjaar:a[d].properties.bouwjaar,status:a[d].properties.status,geometry:a[d].geometry},this.pandobjecten.push(f),WozViewer.WfsService.getVerblijfsObjectsVoorPand(f.identificatie,c,function(a){for(var b=0;b<a.length;b++){var d=a[b];if(null===WozViewer.Filter.Selection.findWozObjectById(d.properties.identificatie))for(var c=d.properties.pandidentificatie,f=0;f<WozViewer.Filter.Selection.pandobjecten.length;f++){var l=WozViewer.Filter.Selection.pandobjecten[f];if(c===l.identificatie){var k=h(d,"Verblijfsobject");
k.geometry=l.geometry;e.push(k)}}}})}},findWozObjectById:function(a){for(var b=0;b<e.length;b++)if(a===e[b].identificatie)return e[b];return null},selectById:function(a,b){var d=this;b&&"Woz"!==b?"Verblijfsobject"==b?WozViewer.WfsService.getBagObjectOpBagId(a,"verblijfsobject",function(a){a&&0<a.length&&(a=h(a[0],b),d.updatePolygoonDetails(a),WozViewer.Filter.Selection.toonVerblijfVoorAdres(a))}):(a=this.findWozObjectById(a),this.setSelectedWoz(a,b)):WozViewer.WfsService.getWozObjectsOpWozId(a,function(a){a=
m(a);a=g(a);d.setSelectedWoz(a,b)})},setSelectedWoz:function(a,b){WozViewer.Util.hideElement("#infoResultaat");a?(c=a,c.type=b,c.actualiteit=WozViewer.Properties.actualiteit,this.updatePolygoonDetails(c),WozViewer.Filter.Selection.toonVerblijfVoorAdres(c),WozViewer.OLMap.drawSelectedFeature(c)):(this.updatePolygoonDetails(null),0<e.length&&(WozViewer.OLMap.layerVerblijfPoint.removeAllFeatures(),WozViewer.OLMap.drawSelectedFeature(e[0])))},setSelectionResult:function(a,c,f){0>=a.length||(b("#polygoon").find(".ui-state-disabled").removeClass("ui-state-disabled"),
a=this.getWozObjecten(a,c,f),a.sort(function(a,b){return a.sortField===b.sortField?0:a.sortField>b.sortField?1:-1}),WozViewer.Filter.Panden.setWozTableData(a),b("#polygoon_woz_table").find("li:first").addClass("row_selected"),0<a.length&&(f=(new OpenLayers.Format.GeoJSON({ignoreExtraDims:!0})).parseGeometry(e[0].geometry),f=f.getCentroid(),WozViewer.OLMap.getBbox().getBounds().contains(f.x,f.y)||WozViewer.Filter.zoomToFilter()),a=1===a.length?a[0]:this.getWozObjectByAddress(a,this.selectedAddress),
this.setSelectedWoz(a,c))},getWozObjectByAddress:function(a,b){if(b&&b!=={})for(var c,d=0;d<a.length;d++)if(c=a[d],c.postcode===b.postcode&&c.huisnummer===b.huisnummer&&c.huisletter===b.huisletter&&c.toevoeging===b.toevoeging)return a[d];return null},updatePolygoonDetails:function(a){var c=b(".detailstable");a?(WozViewer.Util.showElement(c),null===a.wozInfo||0===a.wozInfo.length?b("#polygoon_type").find(".value").html(""):b("#polygoon_type").find(".value").html(a.type.toUpperCase()),b("#polygoon_identificatie").find(".value").html(a.identificatie),
b("#polygoon_status").find(".value").html(a.status),b("#polygoon_adres").find(".value").html(a.adres?a.adres:""),b("#polygoon_postcode").find(".value").html(WozViewer.Util.formatPostCode(a.postcode)),b("#polygoon_woonplaats").find(".value").html(a.woonplaats?a.woonplaats:""),WozViewer.Queryparameters.urlrewrite(WozViewer.OLMap.map.zoom,"??",!0,a.postcode,a.huisnummer,a.huisletter,a.toevoeging,a.adres),WozViewer.Filter.Panden.setWozInfoTableData(a.wozInfo),1>=e.length?WozViewer.Util.hideElement(b("#polygoon_woz_table")):
WozViewer.Util.showElement(b("#polygoon_woz_table")),WozViewer.Util.showElement(b("#polygoon_info_table")),WozViewer.Util.showElement(b("#polygoon_gebruik_table")),WozViewer.Util.showElement(b("#polygoon_adres_table")),WozViewer.Print.setenable(!0),null===a.wozInfo||0===a.wozInfo.length?(WozViewer.Util.hideElement(b("#polygoon_wozwaarde_table")),WozViewer.Util.showElement(b("#polygoon_wozid_table")),WozViewer.Util.showElement(b("#polygoon_wozwaarde_empty")),WozViewer.Util.hideElement(b("#polygoon_identificatie"))):
(WozViewer.Util.showElement(b("#polygoon_wozwaarde_table")),WozViewer.Util.showElement(b("#polygoon_wozid_table")),WozViewer.Util.hideElement(b("#polygoon_wozwaarde_empty")),WozViewer.Util.showElement(b("#polygoon_identificatie")))):WozViewer.Util.hideElement(c)},resetSelectionResult:function(){this.resetPolygoonDetails();WozViewer.OLMap.resetSelectedObject();WozViewer.Filter.Panden.clearSelectionTablePand()},resetPolygoonDetails:function(){b("#polygoon_type").find(".value").html("");b("#polygoon_identificatie").find(".value").html("");
b("#polygoon_status").find(".value").html("");WozViewer.Util.hideElement(b("#polygoon_info_table"));WozViewer.Util.hideElement(b("#polygoon_adres_table"));WozViewer.Util.hideElement(b("#polygoon_woz_table"));WozViewer.Util.showElement(b("#infoResultaat"));WozViewer.Print.setenable(!1);WozViewer.Util.hideElement(b("#polygoon_wozwaarde_table"));WozViewer.Util.hideElement(b("#polygoon_wozid_table"));WozViewer.Util.hideElement(b("#polygoon_wozwaarde_empty"));WozViewer.Util.hideElement(b("#polygoon_gebruik_table"))},
zoomToPolygoon:function(){WozViewer.OLMap.centerFeature(!0)},toonVerblijfVoorAdres:function(a){b("#polygoon_bouwjaar").find(".value").html("");b("#polygoon_gebruiksdoel").find(".value").html("");b("#polygoon_oppervlakte").find(".value").html("");b("#polygoon_bagIdentificatie").find(".value").html("");b("#polygoon_pndIdentificatie").find(".value").html("");WozViewer.OLMap.layerVerblijfPoint.removeAllFeatures();a&&a.postcode&&a.huisnummer&&WozViewer.WfsService.getVerblijfsObjectOpAdres(a,function(c){var f;
if(c&&0<c.length)for(var d=0;d<c.length;d++)if(c[d]&&c[d].properties&&c[d].properties.status&&"Niet gerealiseerd verblijfsobject"!=c[d].properties.status){f=c[d];break}f||(f={});var e=f.properties||{};c=e.bouwjaar||"n.v.t.";var d=e.gebruiksdoel||"n.v.t.",k=e.oppervlakte||"n.v.t.",g=e.identificatie||a.identificatie||"n.v.t.",e=e.pandidentificatie||"n.v.t.";WozViewer.Filter.Selection.getSelectedWoz().gebruiksdoel=d;WozViewer.Filter.Selection.getSelectedWoz().oppervlakte=k;b("#polygoon_bouwjaar").find(".value").html(c);
b("#polygoon_gebruiksdoel").find(".value").html(d);"n.v.t."===k?b("#polygoon_oppervlakte").find(".value").html(k):b("#polygoon_oppervlakte").find(".value").html(k+" mÂ²");b("#polygoon_bagIdentificatie").find(".value").html(g);b("#polygoon_pndIdentificatie").find(".value").html(e);f.geometry&&(WozViewer.OLMap.drawVerblijfsobjectFeature(f),c=f.geometry,f=c.coordinates[0],c=c.coordinates[1],WozViewer.OLMap.getBbox().getBounds().contains(f,c)?WozViewer.OLMap.showLocationOfSelectedVerblijfsobject():WozViewer.OLMap.centerMap(new OpenLayers.LonLat(f,
c),!0,WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL))})},setSelectedAdres:function(a){this.selectedAddress=a||{}},selectObjectByXY:function(a,c,f){b("#dataTablePand").find("a").blur();b("#polygoon").find(".header").addClass("ui-state-disabled");WozViewer.Filter.Selection.selectWozByXY(a,c,f)},selectWozByXY:function(a,b,c){WozViewer.WfsService.getWozObjectsByCoordinates(a,b,c,function(f){f&&0<f.length?WozViewer.Filter.Selection.setSelectionResult(f,"Woz"):WozViewer.Filter.Selection.selectBagByXY(a,b,
c)})},selectBagByXY:function(a,b,c){WozViewer.WfsService.getBagObjectsByCoordinates(a,b,void 0,"pand",function(f){f&&0<f.length?WozViewer.Filter.Selection.setSelectionResult(f,"Pand",c):WozViewer.Filter.Selection.selectLigplaatsByXY(a,b,c)})},selectLigplaatsByXY:function(a,b,c){WozViewer.WfsService.getBagObjectsByCoordinates(a,b,c,"ligplaats",function(f){f&&0<f.length?WozViewer.Filter.Selection.setSelectionResult(f,"Ligplaats"):WozViewer.Filter.Selection.selectStandplaatsByXY(a,b,c)})},selectStandplaatsByXY:function(a,
b,c){WozViewer.WfsService.getBagObjectsByCoordinates(a,b,c,"standplaats",function(a){a&&0<a.length?WozViewer.Filter.Selection.setSelectionResult(a,"Standplaats"):WozViewer.Filter.Selection.resetSelectionResult()})},getSelectedWoz:function(){return c}};return a.Selection})(WozViewer.Filter,jQuery);
WozViewer.Filter.Panden={tableWozwaarde:null,init:function(){$jscomp$this.tableWozwaarde=$("#polygoon_wozwaarde_table").dataTable({bScrollInfinite:!0,bScrollCollapse:!0,iDisplayLength:15,bProcessing:!0,bRetrieve:!0,bLengthChange:!1,bFilter:!1,bSort:!0,paging:!1,iTabIndex:-1,bInfo:!1,bAutoWidth:!1,aaSorting:[[0,"desc"]],aoColumns:[{sTitle:"Peildatum",mRender:function(a,b,c){return WozViewer.Util.formatPeildatum(a)}},{sTitle:"WOZ-waarde",mRender:function(a,b,c){return WozViewer.Util.formatWozWaarde(WozViewer.Util.TryParseInt(a||
0,""))}}]});$(".crosshair","#panden").button();$(".crosshair","#panden").click(function(){return WozViewer.Filter.zoomToFilter()});$(".close","#panden").button();$(".close","#panden").click(function(){WozViewer.Filter.removeFilter();WozViewer.Util.hideElement($("#panden"))})},setWozTableData:function(a){var b=$("#polygoon_woz_table");1>=a.length&&WozViewer.Util.hideElement(b);WozViewer.Util.showElement(b);var c="";$.each(a,function(a,b){c+=sprintf("\x3ca onclick\x3d\"WozViewer.Filter.Selection.selectById('%s', '%s'); return false;\" href\x3d\"#\"\x3e%s\x3c/a\x3e\x3cbr/\x3e",
b.identificatie,b.type?b.type:"Woz",b.adres)});$(b).html(c)},setWozInfoTableData:function(a){$jscomp$this.tableWozwaarde.fnClearTable(0);$jscomp$this.tableWozwaarde.fnDraw(!1);null!==a&&0<a.length&&(a=a.filter(function(a){return void 0!==a}),$jscomp$this.tableWozwaarde.fnAddData(a))},setFilterResult:function(a){if(0===a.length)$("#dataTablePand").html(""),$("#filterNoResults").show();else{$("#filterNoResults").hide();var b='\x3ca href\x3d"#filterSkip" class\x3d"skipLink"\x3eNaar Selectie\x3c/a\x3e';
$.each(a,function(a,e){b+=sprintf("\x3ca onclick\x3d\"WozViewer.Filter.Selection.selectById('%s', 'Woz'); return false;\" href\x3d\"#\"\x3e%s\x3c/a\x3e\x3cbr/\x3e",e.identificatie,e.adres)});$("#dataTablePand").html(b)}},removeDuplicates:function(a){for(var b=[],c=0;c<a.length;c++){var e=a[c].properties.wobj_obj_id;-1!==$.inArray(e,b)?(a.splice(c,1),c--):b.push(e)}},removeDuplicatesPeildatum:function(a){for(var b=[],c=0;c<a.length;c++){var e=a[c][0];-1!==$.inArray(e,b)?(a.splice(c,1),c--):b.push(e)}},
clearSelectionTablePand:function(){},selectTablePand:function(a){}};
(function(a,b){var c=function(a,c,e,d){void 0===d&&(d=!0);b.ajax({type:"POST",contentType:"text/xml",url:WozViewer.Properties.proxyUrl+a,data:c,async:d,success:function(a){"undefined"!==typeof a.error?WozViewer.Util.showServerError(a.error):e(a.features)},error:function(a,b,c){0===a.status&&0===a.readyState||alert("Status: "+b+" : "+c)},dataType:"json",beforeSend:function(a){a.overrideMimeType("Application/json; charset\x3dutf-8")}})},e=function(a,b,c){return'\x3cwfs:GetFeature xmlns:wfs\x3d"http://www.opengis.net/wfs" service\x3d"WFS" version\x3d"1.1.0" xsi:schemaLocation\x3d"http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi\x3d"http://www.w3.org/2001/XMLSchema-instance" outputFormat\x3d"application/json"\x3e\x3cwfs:Query typeName\x3d"'+
a+'" srsName\x3d"EPSG:28992" xmlns:WozViewer\x3d"http://WozViewer.geonovum.nl" xmlns:ogc\x3d"http://www.opengis.net/ogc"\x3e'+(b||"")+(c||"")+"\x3c/wfs:Query\x3e\x3c/wfs:GetFeature\x3e"},g=function(a,b){a=(new OpenLayers.Format.CQL).read(a.trim());a=(new OpenLayers.Format.Filter({defaultVersion:"1.1.0"})).write(a);a=(new OpenLayers.Format.XML).write(a);b&&(a=a.replace('matchCase\x3d"true"','matchCase\x3d"false"'),a=a.replace('matchCase\x3d"false"',""));return a},h=function(a,b,c,d){var f=OpenLayers.String.startsWith(d,
"bag:"),k=f?"geometrie":"wobj_geometrie";a="CONTAINS( "+k+" , POINT("+a+" "+b+")) AND BBOX( "+k+" , "+(""+(a-1)+","+(b-1)+","+(a+1)+","+(b+1))+")";c=g(f?c?a+" AND ( identificatie \x3d "+c+")":a:c?a+" AND ( wobj_bag_obj_id \x3d "+c+")":a);return e(d,c)};a.WfsService={init:function(){console.log("Init WfsService")},getVerblijfsObjectOpAdres:function(a,b){var f=[];a.postcode&&f.push("postcode LIKE '"+a.postcode+"' ");a.huisnummer?f.push("huisnummer \x3d "+a.huisnummer+" "):f.push("(huisnummer IS NULL) ");
a.huisletter?f.push("huisletter \x3d '"+a.huisletter+"' "):f.push("(huisletter IS NULL) ");a.toevoeging?f.push("toevoeging \x3d '"+a.toevoeging+"' "):f.push("(toevoeging IS NULL) ");a=f.join(" AND ");a=g(a,!0);a=e("bag:verblijfsobject",a);c(WozViewer.Properties.bagWfsUrl,a,b)},getWozObjectsByCoordinates:function(a,b,e,d){var f=WozViewer.Properties.wozWfsUrl;a=h(a,b,e,"wozloket:woz_woz_object");c(f,a,d)},getBagObjectsByCoordinates:function(a,b,e,d,g){var f=WozViewer.Properties.bagWfsUrl;a=h(a,b,e,
"bag:"+d);c(f,a,g)},getVerblijfsObjectsVoorPand:function(a,b,h){b=b?"identificatie \x3d "+b+" ":"";a=g(b+(b?" AND ":"")+"(pandidentificatie \x3d "+a+" )",!0);a=e("bag:verblijfsobject",a);c(WozViewer.Properties.bagWfsUrl,a,h,!1)},getWozObjectsOpWozId:function(a,b){a=g("wobj_obj_id\x3d'"+a+"'");a=e("wozloket:woz_woz_object",a);c(WozViewer.Properties.wozWfsUrl,a,b)},getWozObjectOpBagId:function(a,b){a=g("wobj_bag_obj_id\x3d"+a);a=e("wozloket:woz_woz_object",a);c(WozViewer.Properties.wozWfsUrl,a,b)},
getBagObjectOpBagId:function(a,b,h){a=g("identificatie\x3d"+a);b=e("bag:"+b,a);c(WozViewer.Properties.bagWfsUrl,b,h)},filterWozObjects:function(a,b,h){var d=[];a.wozwaardeFrom&&d.push("wobj_huidige_woz_waarde \x3e\x3d "+a.wozwaardeFrom);a.wozwaardeTo&&d.push("wobj_huidige_woz_waarde \x3c\x3d "+a.wozwaardeTo);a.bouwjaarFrom&&d.push("wobj_bouwjaar \x3e\x3d "+a.bouwjaarFrom);a.bouwjaarTo&&d.push("wobj_bouwjaar \x3c\x3d "+a.bouwjaarTo);a.oppervlakteFrom&&d.push("wobj_oppervlakte \x3e\x3d "+a.oppervlakteFrom);
a.oppervlakteTo&&d.push("wobj_oppervlakte \x3c\x3d "+a.oppervlakteTo);b&&d.push("BBOX(wobj_geometrie,"+b.toString()+")");a=0===d.length?"identificatie\x3didentificatie":d.join(" AND ");a=g(a,!0);b=[{name:"wobj_wrd_peildatum",sort:"DESC"},{name:"wobj_straat"},{name:"wobj_huisnummer"},{name:"wobj_huisletter"},{name:"wobj_toevoeging"}];if(null===b||0===b.length)b="";else{for(var d='\x3cogc:SortBy xmlns:ogc\x3d"http://www.opengis.net/ogc"\x3e',f=0;f<b.length;f++)d+='\x3cogc:SortProperty xmlns:ogc\x3d"http://www.opengis.net/ogc"\x3e',
d+='\x3cogc:PropertyName xmlns:ogc\x3d"http://www.opengis.net/ogc"\x3e',d+=b[f].name,d+="\x3c/ogc:PropertyName\x3e",void 0!==b[f].sort&&(d+='\x3cogc:SortOrder xmlns:ogc\x3d"http://www.opengis.net/ogc"\x3e',d+=b[f].sort,d+="\x3c/ogc:SortOrder\x3e"),d+="\x3c/ogc:SortProperty\x3e";b=d+"\x3c/ogc:SortBy\x3e"}a=e("wozloket:woz_woz_object",a,b);c(WozViewer.Properties.filterUrl,a,h)},getActualiteit:function(a){var b=e("wozloket:woz_actualiteit");c(WozViewer.Properties.wozWfsUrl,b,a)}}})(WozViewer,jQuery);
(function(a,b){var c,e=0,g=function(){c.addClass("hidden")};a.BusyIndicator={init:function(){c=b("#busyindicator");b(document).ajaxStart(function(){e++;c.removeClass("hidden")});b(document).ajaxComplete(function(){e--;1>e&&window.setTimeout(g,500)})}}})(WozViewer,jQuery);
WozViewer.Queryparameters={GetURLParameter:function(a){for(var b=window.location.search.substring(1).split("\x26"),c=0;c<b.length;c++){var e=b[c].split("\x3d");if(e[0]==a)return decodeURIComponent(e[1])}},urlrewrite:function(a,b,c,e,g,h,f,k){},process:function(){var a=this.GetURLParameter("locatie");a&&($("input","#geocode").val(a),WozViewer.Geocoder.showSuggestions(a));var b=this.GetURLParameter("bagid");b&&WozViewer.WfsService.getWozObjectOpBagId(b,function(a){if(0<a.length){WozViewer.Filter.Selection.resetSelectionResult();
var c=new OpenLayers.LonLat(a[0].geometry.coordinates[0],a[0].geometry.coordinates[1]);WozViewer.OLMap.layerPolygoon.removeAllFeatures();WozViewer.Filter.Selection.setSelectionResult(a,"Woz");WozViewer.OLMap.centerMap(c,!0,WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL);WozViewer.Filter.Selection.zoomToPolygoon();WozViewer.OLMap.showBAGPanden();WozViewer.OLMap.showVectorLayers();WozViewer.OLMap.layerBRT.redraw();WozViewer.OLMap.layerBag.redraw();WozViewer.OLMap.layerPolygoon.redraw()}else WozViewer.WfsService.getVerblijfsObjectsVoorPand(b,
void 0,function(a){if(0<a.length){a=a[0];var b=a.geometry.coordinates[0],c=a.geometry.coordinates[1];WozViewer.Filter.Selection.setSelectedAdres({postcode:a.properties.postcode,huisnummer:a.properties.huisnummer,huisletter:a.properties.huisletter||"",toevoeging:a.properties.toevoeging||""});WozViewer.Filter.Selection.selectObjectByXY(b,c);WozViewer.OLMap.centerMap(new OpenLayers.LonLat(b,c),!0,WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL)}})});(a=this.GetURLParameter("wozid"))&&WozViewer.WfsService.getWozObjectsOpWozId(a,
function(a){if(0<a.length){WozViewer.Filter.Selection.resetSelectionResult();var b=new OpenLayers.LonLat(a[0].geometry.coordinates[0],a[0].geometry.coordinates[1]);WozViewer.OLMap.layerPolygoon.removeAllFeatures();WozViewer.Filter.Selection.setSelectionResult(a,"Woz");WozViewer.OLMap.centerMap(b,!0,WozViewer.OLMap.VECTOR_LAYERS_MIN_ZOOMLEVEL);WozViewer.Filter.Selection.zoomToPolygoon();WozViewer.OLMap.showBAGPanden()}else WozViewer.Filter.Selection.selectBagByXY(x,y),WozViewer.OLMap.layerBRT.redraw();
WozViewer.OLMap.showVectorLayers();WozViewer.OLMap.layerBRT.redraw();WozViewer.OLMap.layerBag.redraw();WozViewer.OLMap.layerPolygoon.redraw()})}};
WozViewer.Print={init:function(){$("#print").button().click(function(){WozViewer.Print.print(WozViewer.Filter.Selection.getSelectedWoz())});this.setenable(!1);WozViewer.Util.showElement($("#polygoon_print"))},print:function(a){if(null===a||void 0===a)alert("Geen WOZobject geselecteerd");else{var b=WozViewer.OLMap.getBbox(),c=JSON.stringify(a).replace(/'/g,"`");$("body").prepend("\x3cform target\x3d'_pdf_"+a.identificatie+"' method\x3d'post' action\x3d'"+WozViewer.Properties.pdfUrl+"' style\x3d'top:-3333333333px;' id\x3d'tempForm'\x3e\x3cinput type\x3d'hidden' name\x3d'data' value\x3d'"+
c+"'\x3e\x3cinput type\x3d'hidden' name\x3d'bbox' value\x3d'"+b+"'\x3e\x3c/form\x3e");$("#tempForm").submit();$("#tempForm").remove()}},setenable:function(a){a?($("#print").removeAttr("disabled"),$("#print").removeClass("ui-button-disabled"),$("#print").removeClass("ui-state-disabled"),WozViewer.Util.showElement($("#print"))):($("#print").attr("disabled","disabled"),$("#print").addClass("ui-button-disabled ui-state-disabled"),WozViewer.Util.hideElement($("#print")))}};
WozViewer.Popup={tag:[{id:"infoTotstandkoming",title:"Totstandkoming WOZ-waarde",file:"info_totstandkoming.html",extra:15},{id:"infoToelichting",title:"Werking WOZ-waardeloket",file:"info_toelichting.html"},{id:"infoResultaat",title:"Resultaat",file:"info_resultaat.html"},{id:"infoGebruiksvoorwaarden",title:"Gebruiksvoorwaarden WOZ-waardeloket",file:"info_gebruiksvoorwaarden.html"},{id:"infoGeenWozWaarde",title:"Geen WOZ-waarde voor dit pand",file:"info_geenwozwaarde.html"},{id:"filterGeenResultaten",
title:"Geen filter resultaten gevonden",file:"filter_geenresultaten.html"},{id:"helpwozwaarde",title:"WOZ",file:"help_wozwaarde.html",extra:15},{id:"helpkenmerk",title:"Kenmerken",file:"help_kenmerk.html"},{id:"helplocatie",title:"Zoeken op locatie",file:"help_locatie.html"},{id:"helpfilter",title:"Instellen filters om woning(en) te selecteren",file:"help_filter.html"},{id:"helpverversing",title:"Totstandkoming bijgewerkt tot datum",file:"help_verversing.html"}],init:function(){$.each(this.tag,function(a,
b){$.get("resources/txt/"+b.file,function(a){a={id:b.id,title:b.title,text:a,width:60,height:42};b.width&&(a.width=b.width);b.height&&(a.height=b.height);if(!b.width&&!b.height){for(var c=a.text.length,g=70,h=0;30<g&&10>h;)g-=10,h=Math.round(c/g);for(;60<h&&80>g;)g+=10,h=Math.round(c/g);40<h&&(h=40);a.width=g;a.height=b.extra?h+b.extra:h+10}WozViewer.Popup.info.push(a);WozViewer.Popup.fillInfoTags()})});$.each($(".ibutton"),function(a,b){var c=b.id;a=$("#"+c);a.button();a.click(function(){var a=$.grep(WozViewer.Popup.info,
function(a){return a.id===c});0<a.length&&WozViewer.Popup.showPopup(a[0].title,a[0].text,a[0].width,a[0].height)})});WozViewer.Popup.fillInfoTags()},fillInfoTags:function(){$.each($(".info"),function(a,b){var c=b.id;a=$.grep(WozViewer.Popup.info,function(a){return a.id===c});0<a.length&&$("#"+c).html(a[0].text)})},showInformation:function(a){var b=$.grep(WozViewer.Popup.info,function(b){return b.id===a});0<b.length&&WozViewer.Popup.showPopup(b[0].title,b[0].text,b[0].width,b[0].height)},showPopup:function(a,
b,c,e){$.window({draggable:!1,closeOnEscape:!0,resizable:!1,minimizable:!1,maximizable:!1,showModal:!0,frameClass:"infobox",maxHeight:"10em",width:c+"em",height:e+"em",z:6E3,title:a,scrollable:!0,content:"\x3cspan\x3e"+b+"\x3c/span\x3e"})},info:[]};